services:
  postgres:
    image: postgres:15
    container_name: resiflow_postgres
    environment:
      POSTGRES_DB: resiflow
      POSTGRES_USER: resiflow
      POSTGRES_PASSWORD: resiflow
    ports:
      - "5433:5432"   # 👈 IMPORTANT
    volumes:
      - resiflow_pgdata:/var/lib/postgresql/data

volumes:
  resiflow_pgdata:
