spring:
  application:
    name: resiflow
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/resiflow}
    username: ${SPRING_DATASOURCE_USERNAME:resiflow}
    password: ${SPRING_DATASOURCE_PASSWORD:resiflow}
